const assert = require('node:assert/strict');
let passed = 0;
(async () => {
  const { inverseMerge, computeSessionRevert } = await import('../lib/session-revert.js');
  const b = value => value === null ? null : Buffer.from(value);
  const merge = (before, intendedAfter, current, budgets) => inverseMerge({ before: b(before), intendedAfter: b(intendedAfter), current: b(current), budgets });
  function test(name, fn) { fn(); passed++; console.log('ok', passed, name); }
  const scope = { projectId:'p', repoId:null, workspaceId:'w', workspaceEpoch:'e', conversationId:'s', nativeSessionId:'n' };
  const rec = (id, seq, before, after, extra = {}) => ({ operationId:id, workspaceSequence:seq, scope, state:'observed', evidenceLevel:'intent_verified', toolResultObserved:true, attributionGapRevision:0, createdAt:100, before:b(before), intendedAfter:b(after), observedAfter:b(after), ...extra });
  const compute = (records, current, selectedOperationIds = records.map(r => r.operationId), extra = {}) => computeSessionRevert({ records, current:b(current), selectedOperationIds, now:200, ...extra });
  test('dirty preimage preserved', () => assert.equal(merge('user\nold\n','user\nagent\n','user\nagent\n').candidate.toString(),'user\nold\n'));
  test('later independent edit preserved exactly', () => assert.equal(merge('a\nb\nc\n','A\nb\nc\n','A\nb\nC\n').candidate.toString(),'a\nb\nC\n'));
  test('same range refuses', () => assert.equal(merge('a\nb\n','A\nb\n','U\nb\n').status,'refused'));
  test('already reverted noop', () => assert.equal(merge('a','A','a').status,'already_reverted'));
  test('new file moves to recovery', () => assert.equal(merge(null,'new','new').action,'move_to_recovery'));
  test('absent new file noop', () => assert.equal(merge(null,'new',null).status,'already_reverted'));
  test('edited new file refused', () => assert.equal(merge(null,'new','new user').status,'refused'));
  test('deletion unsupported', () => assert.equal(merge('old',null,null).reason,'unsupported_operation'));
  test('missing existing file refuses', () => assert.equal(merge('old','new',null).status,'refused'));
  test('empty preimage is existing file', () => assert.equal(merge('','new','new').action,'replace'));
  test('binary rejects even exact current', () => assert.equal(merge('a\0','b\0','b\0').reason,'unsupported_text'));
  test('invalid utf8 refuses', () => assert.equal(inverseMerge({before:Buffer.from([255]),intendedAfter:b('a'),current:b('a')}).reason,'unsupported_text'));
  test('BOM and mixed EOL exact', () => assert.equal(merge('\ufeffa\r\nb\nc','\ufeffA\r\nb\nc','\ufeffA\r\nb\nC').candidate.toString(),'\ufeffa\r\nb\nC'));
  test('final newline exact', () => assert.equal(merge('a\nb','A\nb','A\nB').candidate.toString(),'a\nB'));
  test('same point insert conflict', () => assert.equal(merge('a\nx\n','a\n','a\nu\n').status,'refused'));
  test('disjoint inserted line survives', () => assert.equal(merge('a\nb\nc\n','A\nb\nc\n','A\nb\nc\nuser\n').candidate.toString(),'a\nb\nc\nuser\n'));
  test('nonunique repeated context refuses', () => assert.equal(merge('x\nx\ny\n','x\ny\n','x\ny\nU\n').reason,'ambiguous_mapping'));
  test('byte limit refuses', () => assert.equal(merge('a','b','b',{maxBytes:0}).reason,'budget_exceeded'));
  test('cell limit refuses', () => assert.equal(merge('a\nb\nc','A\nb\nc','A\nb\nC',{maxCells:1}).reason,'budget_exceeded'));
  test('token limit refuses', () => assert.equal(merge('a\nb','A\nb','A\nb',{maxTokens:1}).reason,'budget_exceeded'));
  test('time limit refuses', () => assert.equal(merge('a','b','b',{maxMs:0}).reason,'budget_exceeded'));
  test('selected simple content eligible', () => assert.equal(compute([rec('1',1,'a','A')],'A').contentEligible,true));
  test('three same-session edits reversed', () => assert.equal(compute([rec('1',1,'a','b'),rec('2',2,'b','c'),rec('3',3,'c','d')],'d').candidate.toString(),'a'));
  test('three edits with independent user intermediate', () => assert.equal(compute([rec('1',1,'a\nx\n','b\nx\n'),rec('2',2,'b\nU\n','c\nU\n'),rec('3',3,'c\nU\n','d\nU\n')],'d\nU\n').candidate.toString(),'a\nU\n'));
  const other = { ...scope, conversationId:'other', nativeSessionId:'other-native' };
  test('other-session disjoint edit retained', () => assert.equal(compute([rec('1',1,'a\nx\n','A\nx\n'),rec('2',2,'A\nx\n','A\nX\n',{scope:other})],'A\nX\n',['1']).candidate.toString(),'a\nX\n'));
  test('other-session overlap refuses and identifies operation', () => assert.deepEqual(compute([rec('1',1,'a','A'),rec('2',2,'A','B',{scope:other})],'B',['1']).conflictOperationIds,['2']));
  test('observed cannot become eligible', () => assert.equal(compute([rec('1',1,'a','A',{evidenceLevel:'observed'})],'A').contentEligible,false));
  test('post mismatch refuses', () => assert.equal(compute([rec('1',1,'a','A',{observedAfter:b('X')})],'A').status,'refused'));
  test('missing final event refuses', () => assert.equal(compute([rec('1',1,'a','A',{toolResultObserved:false})],'A').status,'refused'));
  test('attribution gap refuses', () => assert.equal(compute([rec('1',1,'a','A')],'A',undefined,{gapRevision:1}).reason,'attribution_gap'));
  test('missing selection no evidence', () => assert.equal(compute([],'A',['missing']).reason,'no_evidence'));
  test('duplicate sequence refuses', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',1,'A','B')],'B').status,'refused'));
  test('incomplete intervening operation refuses', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',2,'A','B',{state:'incomplete'})],'B',['1']).status,'refused'));
  test('selected scope cannot cross workspace', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',2,'A','B',{scope:{...scope,workspaceId:'wrong'}})],'B').status,'refused'));
  test('selected scope cannot cross conversation', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',2,'A','B',{scope:other})],'B').status,'refused'));
  test('operation input buffers remain unchanged', () => { const r=rec('1',1,'a','A'); compute([r],'A'); assert.equal(r.before.toString(),'a'); assert.equal(r.intendedAfter.toString(),'A'); });
  test('repeat compute does not invert twice', () => assert.equal(compute([rec('1',1,'a','A')],'a').status,'already_reverted'));
  test('expired evidence refuses', () => assert.equal(compute([rec('1',1,'a','A')],'A',undefined,{now:8*86400000}).reason,'expired_evidence'));
  test('future evidence refuses', () => assert.equal(compute([rec('1',1,'a','A',{createdAt:201})],'A').reason,'expired_evidence'));
  test('aborted result with complete actual mutation eligible', () => assert.equal(compute([rec('1',1,'a','A',{toolOutcome:'aborted'})],'A').contentEligible,true));
  test('prior gap never cleared by capture', () => assert.equal(compute([rec('1',1,'a','A',{attributionGapRevision:5})],'A',undefined,{gapRevision:5}).reason,'attribution_gap'));
  test('rename record refused', () => assert.equal(compute([rec('1',1,'a','A',{kind:'rename'})],'A').reason,'unsupported_operation'));
  test('observed post absent refuses', () => assert.equal(compute([rec('1',1,'a','A',{observedAfter:null})],'A').status,'refused'));
  test('new file with selected later edit moves complete file', () => assert.equal(compute([rec('1',1,null,'a'),rec('2',2,'a','A')],'A').action,'move_to_recovery'));
  test('preexisting untracked treated as replace', () => assert.equal(compute([rec('1',1,'user untracked','agent')],'agent').action,'replace'));
  test('later binary current refuses', () => assert.equal(merge('a','A','A\0').reason,'unsupported_text'));
  test('lone CR preserved', () => assert.equal(merge('a\rb\rc','A\rb\rc','A\rb\rC').candidate.toString(),'a\rb\rC'));
  test('UTF8 Chinese bytes preserved', () => assert.equal(merge('前\n中\n后','改\n中\n后','改\n中\n用户').candidate.toString(),'前\n中\n用户'));
  test('later selected overlap with user gap refuses', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',2,'U','B')],'B').reason,'unproven_continuity'));
  test('later canceled cross-session overlap still refuses', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',2,'A','B',{scope:other}),rec('3',3,'B','A',{scope:other})],'A',['1']).reason,'cross_session_conflict'));
  test('cross-session direct identifier dependency refuses', () => assert.equal(compute([rec('1',1,'function old() {}\nanchor\n','function newApi() {}\nanchor\n'),rec('2',2,'function newApi() {}\nanchor\n','function newApi() {}\nanchor\nnewApi();\n',{scope:other})],'function newApi() {}\nanchor\nnewApi();\n',['1']).reason,'cross_session_conflict'));
  test('short identifier dependency refuses', () => { const A='const x = 1;\nanchor\n', C=A+'console.log(x);\n'; assert.equal(compute([rec('1',1,'placeholder\nanchor\n',A),rec('2',2,A,C,{scope:other})],C,['1']).reason,'cross_session_conflict'); });
  test('changed existing identifier dependency refuses', () => { const B='const threshold = 1;\nanchor\n', A='const threshold = 2;\nanchor\n', C=A+'console.log(threshold);\n'; assert.equal(compute([rec('1',1,B,A),rec('2',2,A,C,{scope:other})],C,['1']).reason,'cross_session_conflict'); });
  test('Unicode identifier dependency refuses', () => { const A='const 阈值 = 2;\nanchor\n', C=A+'console.log(阈值);\n'; assert.equal(compute([rec('1',1,'placeholder\nanchor\n',A),rec('2',2,A,C,{scope:other})],C,['1']).reason,'cross_session_conflict'); });
  test('removed later identifier use remains suspicious dependency', () => { const B='placeholder\nanchor\nconsole.log(x);\n', A='const x = 1;\nanchor\nconsole.log(x);\n', C='const x = 1;\nanchor\n'; assert.equal(compute([rec('1',1,B,A),rec('2',2,A,C,{scope:other})],C,['1']).reason,'cross_session_conflict'); });
  test('nonunique current mapping refuses', () => assert.equal(merge('a\nx\nx\n','A\nx\nx\n','A\nx\n').reason,'ambiguous_mapping'));
  test('selected duplicate IDs refused', () => assert.equal(compute([rec('1',1,'a','A')],'A',['1','1']).reason,'invalid_selection'));
  test('no evidence without records', () => assert.equal(compute([],'A',[]).reason,'no_evidence'));
  test('invalid budget refuses safely', () => assert.equal(merge('a','A','A',{maxCells:NaN}).reason,'budget_exceeded'));
  test('operation budget shared across chain', () => assert.equal(compute([rec('1',1,'a','A'),rec('2',2,'A','B')],'B',undefined,{budgets:{maxOperations:1}}).reason,'budget_exceeded'));
  test('exclusive evidence preserved without invention', () => assert.equal(compute([rec('1',1,'a','A',{evidenceLevel:'exclusive_verified'})],'A').evidenceLevel,'exclusive_verified'));
  test('observed evidence reported as observed when refused', () => assert.equal(compute([rec('1',1,'a','A',{evidenceLevel:'observed'})],'A').evidenceLevel,'observed'));
  test('truthy final-event flag is not final evidence', () => assert.equal(compute([rec('1',1,'a','A',{toolResultObserved:'yes'})],'A').status,'refused'));
  test('nonexistent completed state is not final evidence', () => assert.equal(compute([rec('1',1,'a','A',{state:'completed'})],'A').status,'refused'));
  test('positive record gap cannot be hidden by caller gap zero', () => assert.equal(compute([rec('1',1,'a','A',{attributionGapRevision:1})],'A').reason,'attribution_gap'));
  test('property independent line replacements', () => { for(let i=0;i<16;i++) for(let j=0;j<16;j++) { if(i===j) continue; const B=Array.from({length:16},(_,k)=>`line-${k}\n`), A=B.slice(), C=B.slice(), R=B.slice(); A[i]=`agent-${i}\n`; C[i]=A[i]; C[j]=R[j]=`user-${j}\n`; assert.equal(merge(B.join(''),A.join(''),C.join('')).candidate.toString(),R.join('')); } });
  console.log(`session-revert: ${passed}/${passed} scenarios passed`);
})().catch(error => { console.error(error); process.exitCode=1; });
