/* Offline fixtures pinned to pi-subagents 0.73.1, shared/types.ts at 8a403ef.
 * Never installs extensions, reads agent definitions or starts child models. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
let count = 0;
function check(name, fn) { fn(); count++; console.log('  ok  ' + name); }
(async () => {
  const { JSDOM } = require('jsdom');
  const dom = new JSDOM(fs.readFileSync(path.join(__dirname, '../public/index.html'), 'utf8'), { url: 'http://127.0.0.1/' });
  global.document = dom.window.document; global.window = dom.window;
  const { subagentActivity, subagentNeedsGitRefresh } = await import('../public/subagent-activity.js');
  const { createSubagentObservation, subagentSetup, SUBAGENT_INSTALL_COMMAND, acceptSubagentEvent } = await import('../public/subagent-capabilities.js');
  const model = await import('../public/tool-model.js');
  const view = await import('../public/tool-view.js');
  const entry = (args = {}, id = 'one', name = 'subagent') => model.makeEntry({ toolCallId: id, toolName: name, args }, 1);
  const finish = (e, details, isError = false) => model.applyEnd(e, { result: { content: [{ type: 'text', text: 'RAW_CHILD_SECRET' }], details }, isError }, 10);
  const result = (over = {}) => ({ index: 0, agent: 'custom-reviewer', task: 'Review a module', exitCode: 0, usage: { input: 1, output: 2, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 1 }, ...over });
  const details = { mode: 'single', runId: 'run-one', results: [result({ model: 'provider/model' })] };
  const activity = e => subagentActivity(e);
  check('start', () => assert.equal(activity(entry()).status, 'running'));
  check('success', () => assert.equal(activity(finish(entry(), details)).status, 'success'));
  check('error', () => assert.equal(activity(finish(entry(), null, true)).status, 'error'));
  check('missing agent', () => assert.match(activity(entry()).summary, /Agent unknown/));
  check('missing task', () => assert.match(activity(entry()).summary, /Task unavailable/));
  check('long task bounded preview', () => assert.ok(activity(entry({ task: 'a'.repeat(50000) })).summary.length < 400));
  check('task single line', () => assert.ok(!activity(entry({ task: 'a\nb\tc' })).summary.includes('\n')));
  check('malicious task inert', () => assert.equal(view.renderEntry(entry({ task: '<img onerror="evil()">' })).querySelector('img'), null));
  check('custom agent', () => assert.match(activity(entry({ agent: 'my-agent-中文' })).summary, /my-agent-中文/));
  check('input model never assumed', () => assert.match(activity(entry({ model: 'guessed' })).facts, /Model unknown/));
  check('resolved result model', () => assert.match(activity(finish(entry(), details)).facts, /provider\/model/));
  check('single foreground result', () => assert.match(activity(finish(entry(), details)).facts, /custom-reviewer/));
  const children = { version: 1, parentToolCallId: 'one', workflowRunId: 'wf', inventoryComplete: true, workflowState: 'running', children: [{ childId: 'left', runId: 'r-left', agent: 'custom-a', state: 'completed', model: 'actual-a' }, { childId: 'right', runId: 'r-right', agent: 'custom-b', state: 'running' }] };
  const parallel = entry({ workflowScript: 'return runs.all(secret)' });
  model.applyUpdate(parallel, { partialResult: { content: [], details: { mode: 'workflow', runId: 'wf', results: [], workflowChildren: children } } });
  check('partial structured details retained', () => assert.equal(parallel.details.workflowChildren, children));
  check('workflow child summary', () => assert.match(activity(parallel).facts, /Children: 2/));
  check('workflow authoritative child identities', () => assert.match(activity(parallel).facts, /left.*completed/));
  check('parent relation explicit', () => assert.match(activity(parallel).facts, /Parent tool: one/));
  check('workflow source never projected', () => assert.ok(!JSON.stringify(activity(parallel)).includes('secret')));
  check('unrelated parent summary rejected', () => { const e = entry({}, 'other'); e.details = parallel.details; assert.doesNotMatch(activity(e).facts, /left/); });
  check('no tasks inference', () => assert.doesNotMatch(activity(entry({ tasks: [{ agent: 'fake' }] })).facts, /fake|Children: 1/));
  check('no script count inference', () => assert.doesNotMatch(activity(entry({ workflowScript: 'runs.all([a,b])' })).facts, /Children: 2/));
  const bg = finish(entry({ async: true }), { mode: 'single', results: [], asyncId: 'async-one', runId: 'async-one' });
  check('background launch not completion', () => assert.match(activity(bg).label, /Background launched/));
  check('background actual id', () => assert.match(activity(bg).facts, /async-one/));
  check('requested background without id unknown', () => assert.match(activity(finish(entry({ async: true }), { results: [] })).label, /unconfirmed/));
  check('background missing id not fabricated', () => assert.doesNotMatch(activity(finish(entry({ async: true }), { results: [] })).facts, /Run: one/));
  for (const [s, err] of [['running', false], ['success', false], ['error', true]]) {
    const e = entry({}, 'enable', 'subagents_enable'); if (s !== 'running') finish(e, { enabled: ['subagent'] }, err);
    check('loader ' + s, () => assert.equal(activity(e).status, s));
  }
  check('loader is no execution', () => assert.match(activity(finish(entry({}, 'enable', 'subagents_enable'), { enabled: ['subagent'] })).facts, /No child launched/));
  check('cancel result', () => assert.equal(activity(finish(entry(), { results: [result({ stopped: true })] })).status, 'cancelled'));
  check('interrupted result', () => assert.equal(activity(finish(entry(), { results: [result({ interrupted: true })] })).status, 'interrupted'));
  check('failed child exit', () => assert.equal(activity(finish(entry(), { results: [result({ exitCode: 1 })] })).status, 'error'));
  check('timed out result', () => assert.equal(activity(finish(entry(), { results: [result({ timedOut: true })] })).status, 'error'));
  const missing = model.registerEntry(entry({}, 'missing')); model.settleRunning();
  check('missing end settles spinner', () => assert.equal(activity(missing).status, 'incomplete')); model.clearLiveEntries();
  const history = model.entryFromHistory({ id: 'one', name: 'subagent', arguments: {} }, { details, content: [] }, {});
  check('history same projection', () => assert.equal(activity(history).facts, activity(finish(entry(), details)).facts));
  check('history missing metadata degrades', () => assert.match(activity(model.entryFromHistory({ id: 'h', name: 'subagent' }, { content: [] }, {})).facts, /Model unknown/));
  check('history no fabricated duration', () => assert.equal(view.renderEntry(model.entryFromHistory({ id: 'h', name: 'subagent' }, { content: [] }, {})).querySelector('.tl-time').textContent, ''));
  check('unknown action safely bounded', () => assert.ok(activity(entry({ action: 'unknown'.repeat(2000), env: 'SECRET' })).facts.length < 9000));
  check('generic fallback', () => assert.equal(activity(entry({}, 'generic', 'other_tool')), null));
  const hostile = finish(entry({ env: 'SECRET', auth: 'SECRET', token: 'SECRET' }), { ...details, env: 'SECRET', auth: 'SECRET', token: 'SECRET', results: [result({ messages: [{ content: 'SECRET' }], finalOutput: 'SECRET', transcriptPath: 'SECRET', apiKey: 'SECRET' })] });
  check('secret fields excluded', () => assert.ok(!JSON.stringify(activity(hostile)).includes('SECRET')));
  check('raw details absent DOM', () => assert.ok(!view.renderEntry(hostile).textContent.includes('SECRET')));
  check('raw child output excluded', () => assert.ok(!view.renderEntry(bg).textContent.includes('RAW_CHILD_SECRET')));
  const live = entry({ agent: 'a' }); const node = view.renderEntry(live); document.body.appendChild(node);
  model.applyUpdate(live, { partialResult: { content: [{ type: 'text', text: 'x'.repeat(200000) }], details } }); view.updateEntry(node, live);
  check('update same node', () => assert.equal(document.body.lastChild, node));
  check('progress output bounded', () => assert.ok(node.textContent.length < 9000));
  finish(live, details); view.updateEntry(node, live);
  check('end same node', () => assert.equal(document.body.lastChild, node));
  const second = entry({}, 'two'); const node2 = view.renderEntry(second); document.body.appendChild(node2);
  finish(second, { results: [result({ agent: 'second-agent' })] }); view.updateEntry(node2, second);
  check('independent tool ids', () => assert.notEqual(node.dataset.id, node2.dataset.id));
  check('inverse completion distinct', () => assert.ok(node2.textContent.includes('second-agent') && !node.textContent.includes('second-agent')));
  check('no duplicate DOM', () => assert.equal(document.querySelectorAll('.tl-item').length, 2));
  const o = createSubagentObservation();
  check('unobserved initially', () => assert.equal(o.snapshot(0, 1).subagent, false));
  o.observe({ type: 'tool_execution_start', toolName: 'subagents_enable', bridgeRun: 1 }, 0, 1);
  check('loader != subagent observation', () => assert.equal(o.snapshot(0, 1).subagent, false));
  check('loader observed', () => assert.equal(o.snapshot(0, 1).subagents_enable, true));
  check('workspace stale rejected', () => assert.equal(acceptSubagentEvent({ type: 'tool_execution_end', bridgeRun: 1 }, { switching: true, bridgeRun: 1 }), false));
  check('bridge stale rejected', () => assert.equal(acceptSubagentEvent({ type: 'tool_execution_update', bridgeRun: 1 }, { bridgeRun: 2 }), false));
  check('current event accepted', () => assert.equal(acceptSubagentEvent({ type: 'tool_execution_start', bridgeRun: 2 }, { bridgeRun: 2 }), true));
  check('workspace resets observation', () => assert.equal(o.snapshot(1, 1).subagents_enable, false));
  o.observe({ type: 'tool_execution_start', toolName: 'subagent', bridgeRun: 1 }, 1, 1);
  o.observe({ type: 'bridge_status', state: 'restarting', bridgeRun: 1 }, 1, 1);
  check('restart resets observation', () => assert.equal(o.snapshot(1, 1).subagent, false));
  const installed = { extensions: [{ name: 'pi-subagents', state: { installed: true, enabled: true, loaded: null } }] };
  check('discovery != runtime', () => assert.ok(subagentSetup(installed).installed && !o.snapshot(1, 1).subagent));
  check('missing setup', () => assert.equal(subagentSetup({ extensions: [] }).installed, false));
  check('failed registry unknown', () => assert.equal(subagentSetup({ ok: false }).installed, null));
  check('disabled extension', () => assert.equal(subagentSetup({ extensions: [{ name: 'pi-subagents', state: { installed: true, enabled: false } }] }).configured, false));
  check('loaded unknown remains unknown', () => assert.equal(subagentSetup(installed).loaded, null));
  check('manual install fixed', () => assert.equal(SUBAGENT_INSTALL_COMMAND, 'pi install npm:pi-subagents'));
  check('no automatic install', () => assert.equal(subagentSetup(installed).automaticInstall, false));
  const wait = finish(entry({ id: 'r' }, 'wait', 'bg_wait'), { mode: 'management', results: [], completions: [{ runId: 'r', state: 'completed', success: true, results: [{ agent: 'worker', model: 'actual' }] }] });
  check('bg_wait completion', () => assert.match(activity(wait).facts, /r.*completed/));
  check('bg_wait timeout not child completion', () => assert.match(activity(finish(entry({}, 'wait', 'bg_wait'), { results: [], wait: { reason: 'window_elapsed', timedOut: true, activeRunIds: ['still-running'] } })).facts, /still-running/));
  check('status action', () => assert.match(activity(entry({ action: 'status', id: 'r' })).label, /status/));
  check('steer action safe', () => assert.ok(!JSON.stringify(activity(entry({ action: 'steer', message: 'SECRET' }))).includes('SECRET')));
  check('stop action not GUI kill', () => assert.match(activity(entry({ action: 'stop' })).label, /stop/));
  check('successful foreground Git refresh', () => assert.equal(subagentNeedsGitRefresh(finish(entry(), details)), true));
  check('failed no Git refresh', () => assert.equal(subagentNeedsGitRefresh(finish(entry(), details, true)), false));
  check('launch alone no completion refresh', () => assert.equal(subagentNeedsGitRefresh(bg), false));
  check('wait completion Git refresh', () => assert.equal(subagentNeedsGitRefresh(wait), true));
  check('wait complete spelling retained', () => assert.match(activity(finish(entry({}, 'wait', 'bg_wait'), { completions: [{ runId: 'r', state: 'complete', success: true }] })).facts, /complete · success/));
  check('wait missing state does not invent one', () => assert.match(activity(finish(entry({}, 'wait', 'bg_wait'), { completions: [{ runId: 'r', success: true }] })).facts, /unknown · success/));
  check('partial diff is not Changes evidence', () => { const e = finish(entry(), { ...details, diff: '+fake\n-claim' }); assert.equal(view.renderEntry(e).querySelector('.tl-stat').textContent, ''); });
  check('invalid summary version rejected', () => { const e = entry(); e.details = { workflowChildren: { ...children, version: 99 } }; assert.doesNotMatch(activity(e).facts, /left/); });
  check('same size snapshot content changes', () => { const e = entry(); e.details = { results: [result({ agent: 'AAAA' })] }; const n = view.renderEntry(e); e.details = { results: [result({ agent: 'BBBB' })] }; view.updateEntry(n, e); assert.ok(n.textContent.includes('BBBB') && !n.textContent.includes('AAAA')); });
  const source = fs.readFileSync(path.join(__dirname, '../public/subagent-activity.js'), 'utf8');
  check('no Planner task creation', () => assert.doesNotMatch(source, /fetch\(|planner|createTask|execution_event/));
  check('no Planner mutation', () => assert.doesNotMatch(source, /\bS\.|planId|taskId/));
  /* Parent producer: native-supervisor-channel.ts, 0.73.1 / 8a403ef.
   * Hostile extra fields intentionally exceed its public projection. */
  const supervisor = (action, args = {}) => entry({ action, ...args }, 'supervisor', 'subagent_supervisor');
  const doneSupervisor = (action, d, args = {}, error = false) => finish(supervisor(action, args), d, error);
  const statusDetails = { active: true, pending: 2, root: 'PRIVATE_ROOT' };
  const pendingDetails = { pending: [{ id: 'req-1', runId: 'run-1', agent: 'worker', childIndex: 0, reason: 'need_decision', expectsReply: true, message: 'PRIVATE_QUESTION', requestBody: 'PRIVATE_BODY' }] };
  const replyDetails = { replyTo: 'req-1', runId: 'run-1', agent: 'worker' };
  check('supervisor recognized', () => assert.notEqual(activity(supervisor('status')), null));
  const observed = createSubagentObservation();
  check('supervisor initially unobserved', () => assert.equal(observed.snapshot(0, 1).subagent_supervisor, false));
  observed.observe({ type: 'tool_execution_start', toolName: 'subagent_supervisor', bridgeRun: 1 }, 0, 1);
  check('supervisor observed after start', () => assert.equal(observed.snapshot(0, 1).subagent_supervisor, true));
  check('fresh supervisor does not imply subagent observed', () => assert.equal(observed.snapshot(0, 1).subagent, false));
  observed.observe({ type: 'bridge_status', state: 'restarting', bridgeRun: 1 }, 0, 1);
  check('supervisor restart clears observation', () => assert.equal(observed.snapshot(0, 1).subagent_supervisor, false));
  observed.observe({ type: 'tool_execution_start', toolName: 'subagent_supervisor', bridgeRun: 1 }, 0, 1);
  check('supervisor generation clears observation', () => assert.equal(observed.snapshot(1, 1).subagent_supervisor, false));
  observed.observe({ type: 'tool_execution_start', toolName: 'subagent_supervisor', bridgeRun: 1 }, 1, 2);
  check('supervisor stale bridge rejected', () => assert.equal(observed.snapshot(1, 2).subagent_supervisor, false));
  check('supervisor status start', () => assert.equal(activity(supervisor('status')).label, 'Checking supervisor channel…'));
  check('supervisor status success', () => assert.equal(activity(doneSupervisor('status', statusDetails)).label, 'Checked supervisor channel'));
  check('supervisor pending replies count', () => assert.match(activity(doneSupervisor('status', statusDetails)).facts, /Pending replies: 2/));
  check('supervisor status root excluded', () => assert.ok(!view.renderEntry(doneSupervisor('status', statusDetails)).textContent.includes('PRIVATE_ROOT')));
  check('supervisor pending start', () => assert.equal(activity(supervisor('pending')).label, 'Checking supervisor requests…'));
  check('supervisor pending success', () => assert.equal(activity(doneSupervisor('pending', pendingDetails)).label, 'Checked supervisor requests'));
  check('supervisor pending request count', () => assert.match(activity(doneSupervisor('pending', pendingDetails)).facts, /Pending requests: 1/));
  for (const expected of ['Request: req-1', 'Run: run-1', 'Agent: worker', 'Child index: 0', 'Reason: need_decision', 'Expects reply: true']) {
    check('supervisor safe ' + expected, () => assert.ok(activity(doneSupervisor('pending', pendingDetails)).facts.includes(expected)));
  }
  check('supervisor pending question excluded', () => assert.ok(!view.renderEntry(doneSupervisor('pending', pendingDetails)).textContent.includes('PRIVATE_QUESTION')));
  check('supervisor pending requestBody excluded', () => assert.ok(!view.renderEntry(doneSupervisor('pending', pendingDetails)).textContent.includes('PRIVATE_BODY')));
  check('supervisor list success', () => assert.equal(activity(doneSupervisor('list', pendingDetails)).label, 'Listed supervisor requests'));
  check('supervisor reply start', () => assert.equal(activity(supervisor('reply')).label, 'Replying to subagent…'));
  check('supervisor reply success', () => assert.equal(activity(doneSupervisor('reply', replyDetails)).label, 'Replied to subagent'));
  for (const expected of ['Request: req-1', 'Run: run-1', 'Agent: worker']) {
    check('supervisor reply ' + expected, () => assert.ok(activity(doneSupervisor('reply', replyDetails)).facts.includes(expected)));
  }
  check('supervisor reply input message excluded', () => assert.ok(!view.renderEntry(doneSupervisor('reply', replyDetails, { message: 'PRIVATE_ANSWER', to: 'PRIVATE_TARGET' })).textContent.includes('PRIVATE_')));
  for (const key of ['message', 'root', 'channelDir', 'requestFile', 'replyFile', 'env', 'auth', 'token', 'apiKey', 'credential', 'transcript', 'unknownField']) {
    check('supervisor details field excluded: ' + key, () => { const n = view.renderEntry(doneSupervisor('reply', { ...replyDetails, [key]: 'PRIVATE_VALUE' }, { message: 'PRIVATE_ARGS' })); assert.ok(!n.textContent.includes('PRIVATE_')); assert.equal(n.querySelector('.tl-args').textContent, ''); assert.ok(!n.outerHTML.includes('PRIVATE_')); });
  }
  const unknown = doneSupervisor('something-new', { ...pendingDetails, root: 'PRIVATE_ROOT' }, { message: 'PRIVATE_ANSWER' });
  check('supervisor unknown action safe fallback', () => assert.equal(activity(unknown).label, 'Subagent supervisor action'));
  check('supervisor unknown action bounded', () => assert.ok(activity(supervisor('x'.repeat(10000))).summary.length < 200));
  check('supervisor unknown action named', () => assert.match(activity(unknown).summary, /something-new/));
  check('supervisor unknown action raw input excluded', () => assert.ok(!view.renderEntry(unknown).textContent.includes('PRIVATE_')));
  check('supervisor error label', () => assert.equal(activity(doneSupervisor('reply', { root: 'PRIVATE_ROOT' }, { message: 'PRIVATE_ANSWER' }, true)).label, 'Supervisor action failed'));
  check('supervisor error action and safe output', () => { const n = view.renderEntry(doneSupervisor('reply', { root: 'PRIVATE_ROOT' }, { message: 'PRIVATE_ANSWER' }, true)); assert.ok(n.textContent.includes('Action: reply')); assert.ok(!n.textContent.includes('PRIVATE_') && !n.textContent.includes('RAW_CHILD_SECRET')); });
  for (const [action, d] of [['status', statusDetails], ['pending', pendingDetails], ['list', pendingDetails], ['reply', replyDetails]]) {
    const live = doneSupervisor(action, d, { message: 'PRIVATE_HISTORY' });
    const h = model.entryFromHistory({ id: 'supervisor', name: 'subagent_supervisor', arguments: live.args }, { details: d, content: [{ type: 'text', text: 'PRIVATE_RAW_HISTORY' }] }, {});
    check('supervisor history ' + action, () => { assert.equal(view.renderEntry(h).querySelector('.tl-label').textContent, view.renderEntry(live).querySelector('.tl-label').textContent); assert.equal(activity(h).facts, activity(live).facts); assert.ok(!view.renderEntry(h).textContent.includes('PRIVATE_')); });
  }
  check('supervisor child payload cannot cross adapter', () => { const e = doneSupervisor('status', { ...statusDetails, results: [result({ agent: 'PRIVATE_AGENT' })], progress: [{ currentTool: 'PRIVATE_TOOL' }], workflowChildren: children }); assert.ok(!view.renderEntry(e).textContent.includes('PRIVATE_')); assert.doesNotMatch(activity(e).facts, /left|right/); });
  check('supervisor no completion Git refresh', () => assert.equal(subagentNeedsGitRefresh(doneSupervisor('reply', { ...replyDetails, results: [result()] })), false));
  check('supervisor invalid pending count ignored', () => assert.doesNotMatch(activity(doneSupervisor('status', { pending: -1 })).facts, /Pending replies:/));
  check('supervisor missing pending metadata stays unknown', () => assert.doesNotMatch(activity(doneSupervisor('pending', {})).facts, /Pending requests: 0/));
  check('supervisor missing action safe', () => assert.equal(activity(supervisor(undefined)).label, 'Subagent supervisor action'));
  check('supervisor incomplete does not claim replied', () => { const e = supervisor('reply'); e.status = 'incomplete'; assert.equal(activity(e).label, 'Subagent supervisor action'); assert.equal(activity(e).status, 'incomplete'); });
  check('supervisor prototype action safe', () => assert.equal(activity(supervisor('__proto__')).label, 'Subagent supervisor action'));
  check('supervisor hostile HTML inert', () => assert.equal(view.renderEntry(doneSupervisor('reply', { replyTo: '<img onerror="evil()">' })).querySelector('img'), null));
  check('supervisor row values bounded', () => assert.ok(activity(doneSupervisor('pending', { pending: [{ id: 'a'.repeat(10000), agent: 'b'.repeat(10000), runId: 'c'.repeat(10000), reason: 'd'.repeat(10000) }] })).facts.length < 1500));
  check('supervisor rows bounded', () => assert.ok(activity(doneSupervisor('pending', { pending: Array.from({ length: 1000 }, (_, i) => ({ id: 'req-' + i })) })).facts.length < 8001));
  check('supervisor generic unknown fallback intact', () => assert.match(view.renderEntry(entry({}, 'unknown', 'something_else')).textContent, /执行工具 something_else/));
  const files = fs.readdirSync(path.join(__dirname, '../public')).filter(n => n.startsWith('planner') && n.endsWith('.js'));
  check('Planner source has no supervisor feature', () => { for (const file of files) assert.doesNotMatch(fs.readFileSync(path.join(__dirname, '../public', file), 'utf8'), /subagent_supervisor/); });
  dom.window.close(); console.log(`\n${count}/${count} 通过`);
})().catch(e => { console.error(e); process.exitCode = 1; });
