/* 离线契约：fixture 对照 pi-web-access 0.33.0 的 buildSearchReturn / fetch_content。 */
const assert = require('node:assert/strict');
let count = 0;
const check = (name, fn) => { fn(); count++; console.log('  ok  ' + name); };
(async () => {
  const { JSDOM } = require('jsdom');
  const dom = new JSDOM('<!doctype html><body></body>', { url: 'http://127.0.0.1/' });
  global.document = dom.window.document;
  global.window = dom.window;
  const { webActivity, safeWebUrl, webSourceLink } = await import('../public/web-activity.js');
  const { createWebObservation, webSetup, WEB_INSTALL_COMMAND } = await import('../public/web-capabilities.js');
  const model = await import('../public/tool-model.js');
  const view = await import('../public/tool-view.js');
  const entry = (name, args = {}) => model.makeEntry({ toolCallId: name, toolName: name, args }, 1);
  const end = (e, details, isError = false) => model.applyEnd(e, { result: { content: [{ type: 'text', text: '<script>evil</script> https://body.example' }], details }, isError }, 10);
  for (const name of ['web_search', 'fetch_content', 'get_search_content']) {
    check(name + ' start', () => assert.match(webActivity(entry(name)).label, /…$/));
    check(name + ' success', () => assert.doesNotMatch(webActivity(end(entry(name), {})).label, /…$/));
    check(name + ' error', () => assert.match(webActivity(end(entry(name), {}, true)).label, /failed/));
  }
  check('query/queries', () => assert.equal(webActivity(entry('web_search', { queries: ['a', 'b'] })).summary, 'a · b'));
  check('missing query', () => assert.equal(webActivity(entry('web_search')).summary, 'Query unavailable'));
  check('missing URL', () => assert.equal(webActivity(entry('fetch_content')).summary, 'URL unavailable'));
  check('malformed result', () => assert.deepEqual(webActivity(end(entry('web_search'), 'bad')).sources, []));
  check('unknown provider is not guessed', () => assert.equal(webActivity(end(entry('web_search'), {})).facts.includes('Provider'), false));
  const search = end(entry('web_search'), { totalResults: 2, queryProviders: [{ query: 'a', providers: ['exa'] }], curatedQueries: [{ query: 'a', sources: [{ url: 'https://pi.dev/docs', title: 'Pi docs' }] }] });
  check('structured sources', () => assert.equal(webActivity(search).sources[0].hostname, 'pi.dev'));
  check('actual provider', () => assert.match(webActivity(search).facts, /exa/));
  check('actual count', () => assert.match(webActivity(search).facts, /Results: 2/));
  check('no body regex sources', () => assert.deepEqual(webActivity(end(entry('web_search'), {})).sources, []));
  check('fetch metadata', () => assert.match(webActivity(end(entry('fetch_content'), { urls: ['https://pi.dev'], title: 'Docs', mimeType: 'text/html', status: 200 })).facts, /text\/html/));
  for (const url of ['javascript:alert(1)', 'file:///tmp/a', 'data:text/html,hi', 'ftp://example.org', '//example.org', 'https://user:pass@example.org', 'https://example.org/\nhi', 'bad']) {
    check('reject ' + url.split(':')[0], () => assert.equal(safeWebUrl(url), null));
  }
  for (const url of ['http://example.org', 'https://pi.dev/docs']) check('safe ' + url, () => assert.ok(safeWebUrl(url)));
  check('unknown tool fallback', () => assert.equal(webActivity(entry('custom_search')), null));
  check('cancelled metadata', () => assert.equal(webActivity(end(entry('web_search'), { cancelled: true })).status, 'cancelled'));
  check('extension error metadata', () => assert.equal(webActivity(end(entry('web_search'), { error: 'No query' })).status, 'error'));
  check('abort settles spinner', () => { const e = entry('web_search'); e.status = 'incomplete'; assert.doesNotMatch(webActivity(e).label, /…$/); });
  check('history same adapter', () => { const h = model.entryFromHistory({ id: 'h', name: 'web_search', arguments: {} }, { content: [], details: search.details }, {}); assert.equal(webActivity(h).facts, webActivity(search).facts); });
  check('concurrent identity', () => { const a = entry('web_search', { query: 'A' }); const b = entry('web_search', { query: 'B' }); b.id = 'B'; end(b, {}); assert.equal(webActivity(a).status, 'running'); assert.equal(webActivity(b).summary, 'B'); });
  check('bounded content projection', () => { const e = entry('fetch_content'); e.output = 'x'.repeat(20000); assert.ok(webActivity(e).facts.length < 1000); });
  const o = createWebObservation();
  check('absent setup', () => assert.equal(webSetup({ extensions: [] }).installed, false));
  const registry = { extensions: [{ name: 'pi-web-access', state: { installed: true, enabled: true, loaded: null } }] };
  check('discovered != observed', () => { assert.equal(webSetup(registry).installed, true); assert.equal(o.snapshot(0, 1).web_search, false); });
  check('configured enabled evidence', () => assert.equal(webSetup(registry).configured, true));
  check('discovered but disabled', () => { const s = webSetup({ extensions: [{ name: 'pi-web-access', state: { installed: true, enabled: false } }] }); assert.equal(s.discovered, true); assert.equal(s.configured, false); });
  check('presence cannot infer configuration', () => assert.equal(webSetup({ extensions: [{ name: 'pi-web-access', state: { installed: true, enabled: null } }] }).configured, null));
  check('runtime observation', () => { o.observe({ type: 'tool_execution_start', toolName: 'web_search', bridgeRun: 1 }, 0, 1); assert.equal(o.snapshot(0, 1).web_search, true); });
  check('bridge reset', () => assert.equal(o.snapshot(0, 2).web_search, false));
  check('workspace reset', () => { o.observe({ type: 'tool_execution_start', toolName: 'web_search', bridgeRun: 2 }, 0, 2); assert.equal(o.snapshot(1, 2).web_search, false); });
  check('stale events rejected', () => { o.observe({ type: 'tool_execution_start', toolName: 'web_search', bridgeRun: 1 }, 1, 2); assert.equal(o.snapshot(1, 2).web_search, false); });
  check('restart lifecycle resets', () => { o.observe({ type: 'tool_execution_start', toolName: 'web_search', bridgeRun: 2 }, 1, 2); o.observe({ type: 'bridge_status', state: 'restarting', bridgeRun: 2 }, 1, 2); assert.equal(o.snapshot(1, 2).web_search, false); });
  check('setup failure stays unknown', () => assert.equal(webSetup({ ok: false }).installed, null));
  check('no secrets projected', () => { const e = end(entry('web_search'), { apiKey: 'SECRET', queryProviders: [], token: 'SECRET' }); assert.ok(!JSON.stringify(webActivity(e)).includes('SECRET')); });
  check('fixed install command', () => assert.equal(WEB_INSTALL_COMMAND, 'pi install npm:pi-web-access'));
  check('no install API', () => assert.equal(webSetup(registry).automaticInstall, false));
  const { isSafeWebUrl, isSafeReleaseUrl } = require('../electron/net-probe.cjs');
  check('desktop safe URL', () => assert.equal(isSafeWebUrl('https://pi.dev'), true));
  check('release guard unchanged', () => assert.equal(isSafeReleaseUrl('https://pi.dev'), false));
  check('desktop unsafe URL', () => assert.equal(isSafeWebUrl('javascript:alert(1)'), false));
  check('desktop URL validation parity', () => { for (const url of ['https://pi.dev', 'http://example.org', 'data:a', 'https://u:p@example.org', 'https://example.org/\n']) assert.equal(isSafeWebUrl(url), Boolean(safeWebUrl(url))); });
  let opened = '';
  window.piGuiDesktop = { isDesktop: true, openWebUrl: async url => { opened = url; return { ok: true }; } };
  const link = webSourceLink({ url: 'https://pi.dev', hostname: 'pi.dev', title: '<script>bad</script>' });
  check('source label never HTML', () => assert.equal(link.querySelector('script'), null));
  await link.onclick({ preventDefault() {} });
  check('external link Electron safe path', () => assert.equal(opened, 'https://pi.dev/'));
  check('invalid source no DOM link', () => assert.equal(webSourceLink({ url: 'file:///tmp/a' }), null));
  const live = entry('web_search', { query: 'Pi docs' });
  const node = view.renderEntry(live); document.body.appendChild(node);
  check('DOM start renderer', () => assert.match(node.textContent, /Searching…/));
  model.applyUpdate(live, { partialResult: { content: [{ type: 'text', text: 'x'.repeat(20000) }] } }); view.updateEntry(node, live);
  check('DOM update is bounded', () => assert.ok(node.textContent.length < 2000));
  end(live, search.details); view.updateEntry(node, live);
  check('DOM end same node', () => assert.equal(document.body.querySelectorAll('.tl-item').length, 1));
  check('DOM success with safe sources', () => assert.ok(node.textContent.includes('Searched the web') && node.querySelector('.web-source')));
  check('DOM no unsafe HTML', () => assert.equal(node.querySelector('script'), null));
  const historical = model.entryFromHistory({ id: 'history', name: 'web_search', arguments: live.args }, { details: live.details, content: [] }, {});
  check('DOM history uses same renderer', () => assert.equal(view.renderEntry(historical).querySelector('.tl-label').textContent, node.querySelector('.tl-label').textContent));
  check('DOM unknown fallback', () => assert.match(view.renderEntry(entry('foo_fetch')).textContent, /执行工具 foo_fetch/));
  const setupSource = require('node:fs').readFileSync(require('node:path').join(__dirname, '../public/web-access.js'), 'utf8');
  check('manual install restart delegates to the single shared layout', () => assert.match(setupSource, /from '\.\/ui\/capability-setup\.js'/));
  check('feature module keeps no second restart implementation', () => assert.doesNotMatch(setupSource, /restartBackend/));
  dom.window.close();
  console.log(`\n${count}/${count} 通过`);
})().catch(e => { console.error(e); process.exitCode = 1; });
